name: DISPATCHER

on:
  workflow_dispatch:

jobs:
  dispatch-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger C1 to C9 workflows
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          REPO: ourcaldo/RDPNP
        run: |
          for i in {1..9}
          do
            for ext in yaml yml
            do
              file="C$i.$ext"
              echo "Trying to dispatch $file..."

              response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
                -H "Authorization: token $GITHUB_TOKEN" \
                -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/$REPO/actions/workflows/$file/dispatches \
                -d '{"ref":"main"}')

              if [ "$response" = "204" ]; then
                echo "✅ Successfully dispatched $file"
                break
              else
                echo "❌ Failed dispatch for $file (HTTP $response)"
              fi
            done
          done
