name: Stop All Workflows and Delete History

on:
  workflow_dispatch:  # Manual trigger

jobs:
  stop-and-delete-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel all running workflows
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          REPO: ourcaldo/RDPNP
        run: |
          echo "Fetching all running workflow runs in $REPO..."

          # Get all workflow runs with status in_progress or queued
          runs=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/$REPO/actions/runs?status=in_progress&per_page=100" | jq '.workflow_runs[].id')

          queued=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/$REPO/actions/runs?status=queued&per_page=100" | jq '.workflow_runs[].id')

          all_runs="$runs $queued"

          if [ -z "$all_runs" ]; then
            echo "No running or queued workflows found."
          else
            for run_id in $all_runs; do
              echo "Cancelling workflow run ID: $run_id"
              curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" \
                "https://api.github.com/repos/$REPO/actions/runs/$run_id/cancel"
            done
          fi

      - name: Wait for 60 seconds before deleting history
        run: |
          echo "Waiting 60 seconds to ensure workflows are cancelled..."
          sleep 60

      - name: Delete all workflow history
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          REPO: ourcaldo/RDPNP
        run: |
          echo "Deleting all workflow run histories in $REPO..."

          runs=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/$REPO/actions/runs?per_page=100" | jq '.workflow_runs[].id')

          if [ -z "$runs" ]; then
            echo "No workflow runs to delete."
          else
            for run_id in $runs; do
              echo "Deleting workflow run ID: $run_id"
              curl -s -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
                "https://api.github.com/repos/$REPO/actions/runs/$run_id"
            done
          fi

          echo "✅ All workflow runs deleted and running workflows cancelled."
