name: Delete Workflow History and Stop Itself

on:
  workflow_dispatch:  # Manually triggered

jobs:
  delete-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Delete all workflow runs
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          REPO: ourcaldo/RDPNP
          RUN_ID: ${{ github.run_id }}
        run: |
          echo "Fetching all workflow runs in $REPO..."

          # Fetch all workflow runs (up to 100)
          runs=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/$REPO/actions/runs?per_page=100" | jq '.workflow_runs[].id')

          if [ -z "$runs" ]; then
            echo "No runs found!"
          else
            for run_id in $runs; do
              echo "Deleting workflow run ID: $run_id"
              curl -s -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
                "https://api.github.com/repos/$REPO/actions/runs/$run_id"
            done
          fi

          echo "✅ All workflow runs deleted!"

      - name: Cancel this workflow
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          REPO: ourcaldo/RDPNP
          RUN_ID: ${{ github.run_id }}
        run: |
          echo "Cancelling the current workflow run: $RUN_ID"
          curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/$REPO/actions/runs/$RUN_ID/cancel"
